In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [17]:
### Random data
torch.manual_seed(100)

### Features 5 random normal variables
features = torch.randn((1,5))
print("Shape of Features:", features.shape)
'''Always check the shape of the tensor before multiplying them to 
avoid Matmul conflicts'''
#weights
weights = torch.randn_like(features)
print("Shape of Weights:", weights.shape)
#Bias
bias = torch.randn((1,1))

Shape of Features: torch.Size([1, 5])
Shape of Weights: torch.Size([1, 5])


In [23]:
'''
We are using torch.view in order to reshape[row, col] without altering the values

now we are multiplying features[1,5] * weights[5,1]
'''

y = activation(torch.mm(features, weights.view(5,1))+bias)
y


tensor([[0.3608]])

In [24]:
'''Now as an input we will use a matrix'''
features = torch.randn((1,3))

### Architecure
n_input = features.shape[1] #input units should be equal to the shape of in features. So, 3 inputs.
n_hidden = 2
n_output = 1

# weights
W1 = torch.randn(n_input, n_hidden) # [3,2]
W2 = torch.randn(n_hidden, n_output) # [2, 1]

#Bias 
B1 = torch.randn((1, n_hidden)) # [1, 2]
B2 = torch.randn((1, n_output)) # [1,1]

In [26]:
print("W1: ", W1)
print("W2: ", W2)
print("B1: ",B1)
print("B2: ",B2)

W1:  tensor([[ 0.6587, -0.2586],
        [-0.2510,  0.4770],
        [-0.5883, -0.6131]])
W2:  tensor([[0.4322],
        [0.4612]])
B1:  tensor([[-0.9014, -0.2675]])
B2:  tensor([[0.0756]])


In [29]:
### Using the chain rule for the feed-forward network
layer1 =  activation(torch.mm(features, W1.view(3,2) + B1))
output = activation(torch.mm(layer1, W2) + B2)
print(output)

tensor([[0.6736]])


### Numpy to Torch and Back

In [30]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.3463192 , 0.12217736, 0.29132179],
       [0.74171655, 0.95249641, 0.83609537],
       [0.74220031, 0.52802189, 0.70820781],
       [0.4877793 , 0.98947788, 0.17865372]])

In [31]:
b = torch.from_numpy(a)
b

tensor([[0.3463, 0.1222, 0.2913],
        [0.7417, 0.9525, 0.8361],
        [0.7422, 0.5280, 0.7082],
        [0.4878, 0.9895, 0.1787]], dtype=torch.float64)

In [32]:
b.numpy()

array([[0.3463192 , 0.12217736, 0.29132179],
       [0.74171655, 0.95249641, 0.83609537],
       [0.74220031, 0.52802189, 0.70820781],
       [0.4877793 , 0.98947788, 0.17865372]])